---
- hosts: local
  connection: local
#  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: webservers_sg
    image: ami-0080e4c5bc078760e 
    keypair: rupesh_vir
    region: us-east-1
    count: 1
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 20
        delete_on_termination: true
  vars_files:
    - aws_keys.yml

  tasks:
    - name: Create Launch Configuration
      ec2_lc:
        region: "{{ region }}"
        name: "webapp-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
        image_id: "{{ image }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_group }}"
        volumes: "{{ volumes }}"
        instance_monitoring: yes
