---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_ids:
      - 'i-03140aec11dba11c4'
    security_group: webservers_sg
    image: ami-0080e4c5bc078760e 
    keypair: rupesh_vir
    region: us-east-1
    count: 1
  vars_files:
    - aws_keys.yml

  tasks:
    - name: Start Exisitng EC2 Instances
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_ids: '{{ instance_ids }}' 
        wait: true
        region: "{{ region }}"
        state: running 
      register: ec2

